on: [push, pull_request]
name: Run Go vet
jobs:
  run-go-vet:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.0
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Go vet
        run: go vet .
